### ISSUE TITLE
Advanced where clause showing an error

### ISSUE THREAD

**Issue by VR-Architect** [G4brym/workers-qb#11]
Hi,

I tried the advanced where clause and I am getting an error on the conditions.push('department = ?1') line. The error says "TS2345 (TS) Argument of type 'string' is not assignable to parameter of type 'never'."

Reference:
https://workers-qb.massadas.com/advanced-queries/where/

UPDATE: The command actually works fine if I ignore the error message.

**Comment by VR-Architect** [comment]
Also, when the API doesn't receive a username the code crashes. 

Error:
```
"MSG: D1_ERROR, Stack:Error: D1_ERROR\n    at D1Database._send (d1-beta-facade.entry.js:2113:13)\n    at async D1PreparedStatement.all (d1-beta-facade.entry.js:2151:7)\n    at async user_search (d1-beta-facade.entry.js:1962:19)\n    at async d1-beta-facade.entry.js:2017:19\n    at async d1-beta-facade.entry.js:1435:7\n    at async d1-beta-facade.entry.js:1375:50"
```

Here is my code for review:
```
import { D1QB, OrderTypes } from 'workers-qb'

export async function user_search(c) {
    // page         integer Which page of results to return (! zero-based !)
    // per_page	    integer	How many results to return per page
    // order	    string	Attribute/field name to order the responses by
    // direction    string	Either or ASC or DESC
    const { page, per_page, order_by, direction, username } = await c.req.json()

    // Validate input
    var limit, offset;
    if (isNumeric(per_page)) {
        limit = per_page;
    }
    if (isNumeric(page)) {
        offset = per_page * page;
    }
    const conditions = []
    if (username) {
        conditions.push('Username = ?1')
    }

    const qb = new D1QB(c.env.DB)

    var fields = ['Username, Active, EmailVerified, RealName, Perms, Created_on, Modified_on, Modified_by']

    const fetched = await qb.fetchAll({
        tableName: 'Users',
        fields: fields,
        where: {
            conditions: conditions,
            params: [username],
        },
        //orderBy: { Username: OrderTypes.ASC },
        limit: limit,
        offset: offset
    })
    return fetched.results;
}

function checkIfEmpty(str) {
    if (typeof str === 'string' || str instanceof String) {
        if (!str?.trim() || str.trim().length === 0) {
            return true;
        } else {
            return false;
        }
    }
    return false;
}

function isNumeric(str) {
    if (typeof str == "number") { return true; }
    if (typeof str != "string") return false // we only process strings!  
    return !isNaN(str) && // use type coercion to parse the _entirety_ of the string (`parseFloat` alone does not do this)...
        !isNaN(parseFloat(str)) // ...and ensure strings of whitespace fail
}
```

**Comment by G4brym** [comment]
Hey @VR-Architect that api crash also seams to be on Cloudflare side, if that still happens maybe you should report that on their Discord Server
